//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma2._0.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Diploma2._0.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap angel {
            get {
                object obj = ResourceManager.GetObject("angel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Arrowhead_Down_128 {
            get {
                object obj = ResourceManager.GetObject("Arrowhead_Down_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Arrowhead_Left_01_128 {
            get {
                object obj = ResourceManager.GetObject("Arrowhead-Left-01-128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Arrowhead_Right_01_128 {
            get {
                object obj = ResourceManager.GetObject("Arrowhead-Right-01-128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Camera_01_128 {
            get {
                object obj = ResourceManager.GetObject("Camera-01-128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap changeUser {
            get {
                object obj = ResourceManager.GetObject("changeUser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Check_256__2_ {
            get {
                object obj = ResourceManager.GetObject("Check_256__2_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Click {
            get {
                return ResourceManager.GetStream("Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Document_01_128 {
            get {
                object obj = ResourceManager.GetObject("Document_01_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fon {
            get {
                object obj = ResourceManager.GetObject("fon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap home {
            get {
                object obj = ResourceManager.GetObject("home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] hosts {
            get {
                object obj = ResourceManager.GetObject("hosts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_menu_controlPanel {
            get {
                object obj = ResourceManager.GetObject("icon_menu_controlPanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_menu_goToWindows {
            get {
                object obj = ResourceManager.GetObject("icon_menu_goToWindows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_menu_help {
            get {
                object obj = ResourceManager.GetObject("icon_menu_help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_menu_home {
            get {
                object obj = ResourceManager.GetObject("icon_menu_home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_menu_setting {
            get {
                object obj = ResourceManager.GetObject("icon_menu_setting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_save {
            get {
                object obj = ResourceManager.GetObject("icon_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_setting_avatarUser {
            get {
                object obj = ResourceManager.GetObject("icon_setting_avatarUser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_setting_colorprogram {
            get {
                object obj = ResourceManager.GetObject("icon_setting_colorprogram", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_setting_fonProgram {
            get {
                object obj = ResourceManager.GetObject("icon_setting_fonProgram", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_setting_fontEditor {
            get {
                object obj = ResourceManager.GetObject("icon_setting_fontEditor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE HTML 5.0&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;title&gt;Как востановить пароль&lt;/title&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			body
        ///			{
        ///				font-family: Calibri;
        ///			}
        ///			h1 { text-align: center; }
        ///			hr 
        ///			{
        ///				background: rgba(87, 75, 144, 0.5);
        ///				border: 0px;
        ///				height: 1px;
        ///			}
        ///			span 
        ///			{  
        ///				font-weight: bold;
        ///				margin-left: 15px;
        ///				display: block;
        ///				color: rgb(87, 75, 144);
        ///				padding-top: 15px;
        /// 			}
        ///            p {
        ///                margin-top: 0px;
        ///      [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string inf_RessetPassword {
            get {
                return ResourceManager.GetString("inf_RessetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE HTML 5.0&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;title&gt;Как востановить пароль&lt;/title&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			body
        ///			{
        ///				font-family: Calibri;
        ///			}
        ///			h1 { text-align: center; }
        ///			hr 
        ///			{
        ///				background: rgba(87, 75, 144, 0.5);
        ///				border: 0px;
        ///				height: 1px;
        ///			}
        ///			span 
        ///			{  
        ///				font-weight: bold;
        ///				margin-left: 15px;
        ///				display: block;
        ///				color: rgb(87, 75, 144);
        ///				padding-top: 15px;
        /// 			}
        ///			p
        ///			{
        ///				font-size: 1.5em;
        ///				text-align: justi [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string info_deleteProgram {
            get {
                return ResourceManager.GetString("info_deleteProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE HTML 5.0&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;title&gt;Как востановить пароль&lt;/title&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			body
        ///			{
        ///				font-family: Calibri;
        ///			}
        ///			h1 { text-align: center; }
        ///			hr 
        ///			{
        ///				background: rgba(87, 75, 144, 0.5);
        ///				border: 0px;
        ///				height: 1px;
        ///			}
        ///			span 
        ///			{  
        ///				font-weight: bold;
        ///				margin-left: 15px;
        ///				display: block;
        ///				color: rgb(87, 75, 144);
        ///				padding-top: 15px;
        /// 			}
        ///			p
        ///			{
        ///				font-size: 1.5em;
        ///				text-align: justi [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string info_editSettingChild {
            get {
                return ResourceManager.GetString("info_editSettingChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info_firststep_autenficatio {
            get {
                object obj = ResourceManager.GetObject("info_firststep_autenficatio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info_firststep_errorLogin {
            get {
                object obj = ResourceManager.GetObject("info_firststep_errorLogin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info_firststep_privateAccount {
            get {
                object obj = ResourceManager.GetObject("info_firststep_privateAccount", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE HTML 5.0&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;title&gt;Как востановить пароль&lt;/title&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			img
        ///			{
        ///				max-width: 850px;
        ///			}
        ///			body
        ///			{
        ///				font-family: Calibri;
        ///			}
        ///			h1 { text-align: center; }
        ///			img
        ///			{
        ///				display: block;
        ///				margin: auto;
        ///			}
        ///			hr 
        ///			{
        ///				background: rgba(87, 75, 144, 0.5);
        ///				border: 0px;
        ///				height: 1px;
        ///			}
        ///			span 
        ///			{  
        ///				font-size: 1.5em;
        ///				font-weight: bold;
        ///				margin-left: 15px;
        ///				display: [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string info_FirstSteps {
            get {
                return ResourceManager.GetString("info_FirstSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE HTML 5.0&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;title&gt;Как востановить пароль&lt;/title&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			body
        ///			{
        ///				font-family: Calibri;
        ///			}
        ///			h1 { text-align: center; }
        ///			hr 
        ///			{
        ///				background: rgba(87, 75, 144, 0.5);
        ///				border: 0px;
        ///				height: 1px;
        ///			}
        ///			span 
        ///			{  
        ///				font-weight: bold;
        ///				margin-left: 15px;
        ///				display: block;
        ///				color: rgb(87, 75, 144);
        ///				padding-top: 15px;
        /// 			}
        ///			p
        ///			{
        ///				font-size: 1.5em;
        ///				text-align: justi [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string info_hearingProblems {
            get {
                return ResourceManager.GetString("info_hearingProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE HTML 5.0&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;title&gt;Как востановить пароль&lt;/title&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			body
        ///			{
        ///				font-family: Calibri;
        ///			}
        ///			h1 { text-align: center; }
        ///			hr 
        ///			{
        ///				background: rgba(87, 75, 144, 0.5);
        ///				border: 0px;
        ///				height: 1px;
        ///			}
        ///			span 
        ///			{  
        ///				font-weight: bold;
        ///				margin-left: 15px;
        ///				display: block;
        ///				color: rgb(87, 75, 144);
        ///				padding-top: 15px;
        /// 			}
        ///			p
        ///			{
        ///				font-size: 1.5em;
        ///				text-align: justi [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string info_problemsAutenfication {
            get {
                return ResourceManager.GetString("info_problemsAutenfication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE HTML 5.0&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;title&gt;Как востановить пароль&lt;/title&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			body
        ///			{
        ///				font-family: Calibri;
        ///			}
        ///			h1 { text-align: center; }
        ///			hr 
        ///			{
        ///				background: rgba(87, 75, 144, 0.5);
        ///				border: 0px;
        ///				height: 1px;
        ///			}
        ///			span 
        ///			{  
        ///				font-weight: bold;
        ///				margin-left: 15px;
        ///				display: block;
        ///				color: rgb(87, 75, 144);
        ///				padding-top: 15px;
        /// 			}
        ///			p
        ///			{
        ///				font-size: 1.5em;
        ///				text-align: justi [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string info_RessetPassword {
            get {
                return ResourceManager.GetString("info_RessetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE HTML 5.0&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;meta charset=&quot;utf-8&quot;&gt;
        ///		&lt;title&gt;Как востановить пароль&lt;/title&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///			body
        ///			{
        ///				font-family: Calibri;
        ///				padding: 10px;
        ///			}
        ///			h1 { text-align: center; }
        ///			hr 
        ///			{
        ///				background: rgba(87, 75, 144, 0.5);
        ///				border: 0px;
        ///				height: 1px;
        ///			}
        ///			span 
        ///			{  
        ///				font-weight: bold;
        ///				margin-left: 15px;
        ///				display: block;
        ///				color: rgb(87, 75, 144);
        ///				padding-top: 15px;
        ///				font-size: 1.6em;
        /// 			}
        ///			p
        ///			{
        ///	 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string info_updateProgram {
            get {
                return ResourceManager.GetString("info_updateProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Left_Arrow_128 {
            get {
                object obj = ResourceManager.GetObject("Left_Arrow_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lockLogin {
            get {
                object obj = ResourceManager.GetObject("lockLogin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_Daniil {
            get {
                object obj = ResourceManager.GetObject("logo_Daniil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LogOut {
            get {
                object obj = ResourceManager.GetObject("LogOut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logout_128 {
            get {
                object obj = ResourceManager.GetObject("Logout_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Message_Mail_128 {
            get {
                object obj = ResourceManager.GetObject("Message_Mail_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newUser1 {
            get {
                object obj = ResourceManager.GetObject("newUser1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap offPc {
            get {
                object obj = ResourceManager.GetObject("offPc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap reboot {
            get {
                object obj = ResourceManager.GetObject("reboot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap setting {
            get {
                object obj = ResourceManager.GetObject("setting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sleepMode {
            get {
                object obj = ResourceManager.GetObject("sleepMode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap specIcon {
            get {
                object obj = ResourceManager.GetObject("specIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
